#This may need checking on other systems, because I'm using exact value checks with no consideration of precision...
#Rather strange to test entropy when you know it's wrong!...
#Setup
require(testthat)
require(picante)
require(pez)
require(caper)
data(phylocom)
data <- comparative.comm(phylocom$phylo, phylocom$sample, warn=FALSE)
context("evenness metrics")

#Tests
test_that("Rao", {
  rao_test <<- evenness(data, "rao")
  expect_that(rao_test$rao, is_equivalent_to(c(2.125, 2.47222222222222, 2.91666666666667, 3.47222222222222, 3.875, 3.5546875)))
  expect_that(names(rao_test$rao), equals(rownames(data$comm)))
  expect_that(rao_test$delta, equals(NULL))
  expect_that(rao_test$entropy, equals(NULL))
  expect_that(rao_test$cadotte, equals(NULL))
  expect_that(rao_test$pst, equals(NULL))
  expect_that(rao_test$taxon, equals(NULL))
  expect_that(rao_test$rao, is_equivalent_to(rao_test$coefs$rao))
  expect_that(rao_test$mpd, equals(NULL))
})

test_that("taxon", {
  set.seed(123)
  taxon_test <<- evenness(data, "taxon")
  expect_that(taxon_test$rao, equals(NULL))
  expect_that(taxon_test$taxon$Species, is_equivalent_to(c(8, 8, 8, 8, 8, 8)))
  expect_that(names(taxon_test$taxon$Species), equals(rownames(data$comm)))
  expect_that(taxon_test$taxon, equals(taxondive(data$comm, cophenetic(data$phy))))
  expect_that(taxon_test$entropy, equals(NULL))
  expect_that(taxon_test$cadotte, equals(NULL))
  expect_that(taxon_test$pst, equals(NULL))
  expect_that(taxon_test$coefs$Delta, is_equivalent_to(taxon_test$taxon$D[1:6]))
  expect_that(taxon_test$coefs$DeltaStar, is_equivalent_to(taxon_test$taxon$Dstar[1:6]))
  expect_that(taxon_test$coefs$LambdaPlus, is_equivalent_to(taxon_test$taxon$Lambda[1:6]))
  expect_that(taxon_test$coefs$DeltaPlus, is_equivalent_to(taxon_test$taxon$Dplus[1:6]))
  expect_that(taxon_test$coefs$S.DeltaPlus, is_equivalent_to(taxon_test$taxon$SDplus[1:6]))
  expect_that(taxon_test$mpd, equals(NULL))
})

test_that("Entropy", {
  entropy_test <<- evenness(data, "entropy")
  expect_that(entropy_test$rao, equals(NULL))
  expect_that(entropy_test$delta, equals(NULL))
  expect_that(entropy_test$entropy, is_equivalent_to(c(NA, NA, NA, NA, NA, NA, 3.63902269793971, 4.62549821485909, 5.2620123831539, 6.64830674427379, 8.31776616671934, 7.22716285080812)))
  expect_that(entropy_test$cadotte, equals(NULL))
  expect_that(entropy_test$pst, equals(NULL))
  expect_that(entropy_test$taxon, equals(NULL))
  expect_that(entropy_test$entropy, is_equivalent_to(entropy_test$coefs$entropy))
  expect_that(entropy_test$mpd, equals(NULL))
})

test_that("Cadotte", {
  cadotte_test <<- evenness(data, "cadotte")
  expect_that(cadotte_test$rao, equals(NULL))
  expect_that(cadotte_test$delta, equals(NULL))
  expect_that(cadotte_test$entropy, equals(NULL))
  
  expect_that(cadotte_test$cadotte$PAE, is_equivalent_to(c(-0.3125, 0, 0.0555555555555556, 0.227272727272727, 0.366666666666667, 0.666666666666667)))
  expect_that(cadotte_test$cadotte$IAC, is_equivalent_to(c(0.5, 0.75, 0.75, 0.6875, 0.416666666666667, 0.916666666666667)))
  expect_that(cadotte_test$cadotte$Haed, is_equivalent_to(c(c(2.07944154167984, 2.43261844647745, 2.42601513195981, 2.42601513195981, 2.07944154167984, 2.67765404685526))))
  expect_that(cadotte_test$cadotte$Eaed, is_equivalent_to(c(1, 0.978957679027899, 0.976300309778954, 
0.976300309778954, 1, 0.965759553653586)))
  expect_that(rownames(cadotte_test$cadotte), equals(rownames(data$comm)))
  expect_that(colnames(cadotte_test$cadotte), equals(c("PAE", "IAC", "Haed", "Eaed")))
  expect_that(cadotte_test$pst, equals(NULL))
  expect_that(entropy_test$taxon, equals(NULL))
  expect_that(cadotte_test$cadotte, is_equivalent_to(cadotte_test$coefs[,c("PAE", "IAC", "Haed", "Eaed")]))
  expect_that(entropy_test$mpd, equals(NULL))
})

test_that("Pst", {
  pst_test <<- evenness(data, "pst")
  expect_that(pst_test$rao, equals(NULL))
  expect_that(pst_test$delta, equals(NULL))
  expect_that(pst_test$entropy, equals(NULL))
  expect_that(pst_test$cadotte, equals(NULL))
  expect_that(pst_test$pst, is_equivalent_to(c(4.25, 4.94444444444444, 5.83333333333333, 6.94444444444444, 7.75, 7.109375)))
  expect_that(pst_test$taxon, equals(NULL))
  expect_that(pst_test$pst, is_equivalent_to(pst_test$coefs$pst))
  expect_that(pst_test$mpd, equals(NULL))
})

test_that("Delta", {
  set.seed(123)
  delta_test <<- evenness(data, "delta")
  expect_that(delta_test$rao, equals(NULL))
  expect_that(delta_test$taxon, equals(NULL))
  expect_that(delta_test$entropy, equals(NULL))
  expect_that(delta_test$cadotte, equals(NULL))
  expect_that(delta_test$pst, equals(NULL))
  expect_that(delta_test$taxon, equals(NULL))
  expect_that(delta_test$delta$values, equals(c(NA, 1e-06, 1e-06, 1e-06, NA, 3)))
  expect_that(delta_test$delta$models[[1]], equals(NA))
  expect_that(coef(delta_test$delta$models[[2]]), is_equivalent_to(1.5))
  expect_that(delta_test$lambda, equals(NULL))
  expect_that(delta_test$kappa, equals(NULL))
  expect_that(delta_test$delta$values, is_equivalent_to(delta_test$coefs$delta))
  expect_that(entropy_test$mpd, equals(NULL))
})

test_that("Kappa", {
  set.seed(123)
  kappa_test <<- evenness(data, "kappa")
  expect_that(kappa_test$rao, equals(NULL))
  expect_that(kappa_test$delta, equals(NULL))
  expect_that(kappa_test$entropy, equals(NULL))
  expect_that(kappa_test$cadotte, equals(NULL))
  expect_that(kappa_test$pst, equals(NULL))
  expect_that(kappa_test$taxon, equals(NULL))
  expect_that(kappa_test$kappa$values, equals(c(NA, 3, 3, 3, NA, 1.65281212634147)))
  expect_that(kappa_test$kappa$models[[1]], equals(NA))
  expect_that(coef(kappa_test$kappa$models[[2]]), is_equivalent_to(1.5))
  expect_that(kappa_test$lambda, equals(NULL))
  expect_that(kappa_test$delta, equals(NULL))
  expect_that(kappa_test$kappa$values, is_equivalent_to(kappa_test$coefs$kappa))
  expect_that(entropy_test$mpd, equals(NULL))
})

test_that("Lambda", {
  set.seed(123)
  lambda_test <<- evenness(data, "lambda")
  expect_that(lambda_test$rao, equals(NULL))
  expect_that(lambda_test$delta, equals(NULL))
  expect_that(lambda_test$entropy, equals(NULL))
  expect_that(lambda_test$cadotte, equals(NULL))
  expect_that(lambda_test$pst, equals(NULL))
  expect_that(lambda_test$taxon, equals(NULL))
  expect_that(lambda_test$lambda$values, equals(c(NA, 1, 1, 1, NA, 1e-06)))
  expect_that(lambda_test$lambda$models[[1]], equals(NA))
  expect_that(coef(lambda_test$lambda$models[[2]]), is_equivalent_to(1.5))
  expect_that(lambda_test$kappa, equals(NULL))
  expect_that(lambda_test$delta, equals(NULL))
  expect_that(lambda_test$lambda$values, is_equivalent_to(lambda_test$coefs$lambda))
  expect_that(lambda_test$mpd, equals(NULL))
})

test_that("MPD", {
  mpd_test <<- evenness(data, "mpd")
  expect_that(mpd_test$rao, equals(NULL))
  expect_that(mpd_test$delta, equals(NULL))
  expect_that(mpd_test$entropy, equals(NULL))
  expect_that(mpd_test$cadotte, equals(NULL))
  expect_that(mpd_test$pst, equals(NULL))
  expect_that(mpd_test$taxon, equals(NULL))
  expect_that(mpd_test$lambda, equals(NULL))
  expect_that(lambda_test$kappa, equals(NULL))
  expect_that(mpd_test$delta, equals(NULL))
  expect_that(mpd_test$mpd, is_equivalent_to(mpd_test$coefs$mpd))
  expect_that(mpd_test$mpd, equals(c(c(4.25, 4.94444444444444, 5.83333333333333, 6.94444444444444, 7.75, 7.109375))))
})

test_that("Each measure is the same as calculated together (where can)", {
  all_test <- evenness(data)
  expect_that(rao_test$rao, equals(all_test$rao))
  expect_that(delta_test$delta, equals(all_test$delta))
  expect_that(entropy_test$entropy, equals(all_test$entropy))
  expect_that(cadotte_test$cadotte, equals(all_test$cadotte))
  expect_that(pst_test$pst, equals(all_test$pst))
  expect_that(delta_test$delta, equals(all_test$delta))
  expect_that(all_test$coefs, equals(coef(all_test)))
})
