#This may need checking on other systems, because I'm using exact value checks with no consideration of precision...
#Setup
require(testthat)
require(pez)
require(picante)
data(phylocom)
data <- comparative.comm(phylocom$phylo, phylocom$sample, warn=FALSE)
context("shape metrics")

#Tests
test_that("PSV", {
  psv_test <<- shape(data, "psv")
  expect_that(psv_test$psv, equals(c(0.485714285714286, 0.6, 0.714285714285714, 0.828571428571429, 0.885714285714286, 0.842857142857143)))
  expect_that(psv_test$psr, equals(NULL))
  expect_that(psv_test$mpd, equals(NULL))
  expect_that(psv_test$pd, equals(NULL))
  expect_that(psv_test$pd.ivs, equals(NULL))
  expect_that(psv_test$colless, equals(NULL))
  expect_that(psv_test$gamma, equals(NULL))
  expect_that(psv_test$taxon, equals(NULL))
  expect_that(psv_test$eigen.sum, equals(NULL))
  expect_that(psv_test$cadotte.pd, equals(NULL))
  expect_that(psv_test$psv, equals(psv_test$coefs$psv))
})
test_that("PSR", {
  psr_test <<- shape(data, "psr")
  expect_that(psr_test$psv, equals(NULL))
  expect_that(psr_test$psr, equals(c(3.88571428571429, 4.8, 5.71428571428571, 6.62857142857143, 7.08571428571429, 6.74285714285714)))
  expect_that(psr_test$mpd, equals(NULL))
  expect_that(psr_test$pd, equals(NULL))
  expect_that(psr_test$pd.ivs, equals(NULL))
  expect_that(psr_test$colless, equals(NULL))
  expect_that(psr_test$gamma, equals(NULL))
  expect_that(psr_test$taxon, equals(NULL))
  expect_that(psr_test$eigen.sum, equals(NULL))
  expect_that(psr_test$cadotte.pd, equals(NULL))
  expect_that(psr_test$psr, equals(psr_test$coefs$psr))
})
test_that("MPD", {
  mpd_test <<- shape(data, "mpd")
  expect_that(mpd_test$psv, equals(NULL))
  expect_that(mpd_test$psr, equals(NULL))
  expect_that(mpd_test$mpd, equals(c(4.85714285714286, 6, 7.14285714285714, 8.28571428571429, 8.85714285714286, 8.42857142857143)))
  expect_that(mpd_test$pd, equals(NULL))
  expect_that(mpd_test$pd.ivs, equals(NULL))
  expect_that(mpd_test$colless, equals(NULL))
  expect_that(mpd_test$gamma, equals(NULL))
  expect_that(mpd_test$taxon, equals(NULL))
  expect_that(mpd_test$eigen.sum, equals(NULL))
  expect_that(mpd_test$cadotte.pd, equals(NULL))
  expect_that(mpd_test$mpd, equals(mpd_test$coefs$mpd))
})
test_that("PD", {
  pd_test <<- shape(data, "pd")
  expect_that(pd_test$psv, equals(NULL))
  expect_that(pd_test$psr, equals(NULL))
  expect_that(pd_test$mpd, equals(NULL))
  expect_that(pd_test$pd, equals(c(16, 17, 18, 22, 30, 27)))
  expect_that(pd_test$pd.ivs, is_equivalent_to(c(-5.66666666666666, -4.66666666666667, -3.66666666666667, 0.333333333333332, 8.33333333333333, 5.33333333333333)))
  expect_that(pd_test$colless, equals(NULL))
  expect_that(pd_test$gamma, equals(NULL))
  expect_that(pd_test$taxon, equals(NULL))
  expect_that(pd_test$eigen.sum, equals(NULL))
  expect_that(pd_test$cadotte.pd, equals(NULL))
  expect_that(pd_test$pd, is_equivalent_to(pd_test$coefs$pd))
  expect_that(pd_test$pd.ivs, is_equivalent_to(pd_test$coefs$pd.ivs))
})
test_that("Colless", {
  colless_test <<- shape(data, "colless")
  expect_that(colless_test$psv, equals(NULL))
  expect_that(colless_test$psr, equals(NULL))
  expect_that(colless_test$mpd, equals(NULL))
  expect_that(colless_test$pd, equals(NULL))
  expect_that(colless_test$pd.ivs, equals(NULL))
  expect_that(colless_test$colless, is_equivalent_to(c(0, 0, 0, 0, 0, 5)))
  expect_that(colless_test$gamma, equals(NULL))
  expect_that(colless_test$taxon, equals(NULL))
  expect_that(colless_test$eigen.sum, equals(NULL))
  expect_that(colless_test$cadotte.pd, equals(NULL))
  expect_that(colless_test$colless, is_equivalent_to(colless_test$coefs$colless))
})
test_that("Gamma", {
  gamma_test <<- shape(data, "gamma")
  expect_that(gamma_test$psv, equals(NULL))
  expect_that(gamma_test$psr, equals(NULL))
  expect_that(gamma_test$mpd, equals(NULL))
  expect_that(gamma_test$pd, equals(NULL))
  expect_that(gamma_test$pd.ivs, equals(NULL))
  expect_that(gamma_test$colless, equals(NULL))
  expect_that(gamma_test$gamma, is_equivalent_to(c(-1.41421356237309, -0.707106781186547, -0.157134840263678, 
-0.385694607919935, -2.9227080289044, -2.19988776369148)))
  expect_that(gamma_test$taxon, equals(NULL))
  expect_that(gamma_test$eigen.sum, equals(NULL))
  expect_that(gamma_test$cadotte.pd, equals(NULL))
  expect_that(gamma_test$gamma, is_equivalent_to(gamma_test$coefs$gamma))
})
test_that("Taxon", {
  taxon_test <<- shape(data, "taxon")
  expect_that(taxon_test$psv, equals(NULL))
  expect_that(taxon_test$psr, equals(NULL))
  expect_that(taxon_test$mpd, equals(NULL))
  expect_that(taxon_test$pd, equals(NULL))
  expect_that(taxon_test$pd.ivs, equals(NULL))
  expect_that(taxon_test$colless, equals(NULL))
  expect_that(taxon_test$gamma, equals(NULL))
  t <- data
  t$comm[t$comm > 0] <- 1
  expect_that(taxon_test$taxon, equals(taxondive(t$comm, cophenetic(data$phy))))
  expect_that(taxon_test$eigen.sum, equals(NULL))
  expect_that(taxon_test$cadotte.pd, equals(NULL))
  expect_that(taxon_test$coefs$Delta, is_equivalent_to(taxon_test$taxon$D[1:6]))
  expect_that(taxon_test$coefs$DeltaStar, is_equivalent_to(taxon_test$taxon$Dstar[1:6]))
  expect_that(taxon_test$coefs$LambdaPlus, is_equivalent_to(taxon_test$taxon$Lambda[1:6]))
  expect_that(taxon_test$coefs$DeltaPlus, is_equivalent_to(taxon_test$taxon$Dplus[1:6]))
  expect_that(taxon_test$coefs$S.DeltaPlus, is_equivalent_to(taxon_test$taxon$SDplus[1:6]))
})
test_that("Eigenvectors", {
  set.seed(123)
  eigen.sum <<- shape(data, "eigen.sum")
  expect_that(eigen.sum$psv, equals(NULL))
  expect_that(eigen.sum$psr, equals(NULL))
  expect_that(eigen.sum$mpd, equals(NULL))
  expect_that(eigen.sum$pd, equals(NULL))
  expect_that(eigen.sum$pd.ivs, equals(NULL))
  expect_that(eigen.sum$colless, equals(NULL))
  expect_that(eigen.sum$gamma, equals(NULL))
  expect_that(eigen.sum$taxon, equals(NULL))
  expect_that(eigen.sum$eigen.sum, is_equivalent_to(c(1.85989806057967e-32, 9.80257655161354e-05, 0.0580509448862977, 
0.0456171567606935, 0.0434666292330911, 0.0476659578856296)))
  set.seed(123)
  expect_that(shape(data, "eigen.sum", 2)$eigen.sum, is_equivalent_to(c(3.30159419037812e-32, 0.082086748214039, 0.0137252988148037, 0.0415764004365078, 0.0384905400587625, 0.0452932152543931)))
  expect_that(eigen.sum$cadotte.pd, equals(NULL))
  expect_that(eigen.sum$eigen.sum, is_equivalent_to(eigen.sum$coefs$eigen.sum))
})
test_that("Cadotte PD", {
  cadotte.pd <<- shape(data, "cadotte.pd")
  expect_that(cadotte.pd$psv, equals(NULL))
  expect_that(cadotte.pd$psr, equals(NULL))
  expect_that(cadotte.pd$mpd, equals(NULL))
  expect_that(cadotte.pd$pd, equals(NULL))
  expect_that(cadotte.pd$pd.ivs, equals(NULL))
  expect_that(cadotte.pd$colless, equals(NULL))
  expect_that(cadotte.pd$gamma, equals(NULL))
  expect_that(cadotte.pd$taxon, equals(NULL))
  expect_that(cadotte.pd$eigen.sum, equals(NULL))
  expect_that(rownames(cadotte.pd$cadotte.pd), equals(rownames(data$comm)))
  expect_that(colnames(cadotte.pd$cadotte.pd), equals(c("Eed", "Hed")))
  expect_that(cadotte.pd$cadotte.pd$Eed, equals(c(3.202317, 3.104838, 3.013283, 2.697896, 2.241960, 2.391608), tolerance=0.00001))
  expect_that(cadotte.pd$cadotte.pd$Hed, equals(c(6.659032, 6.456330, 6.265945, 5.610116, 4.662026, 4.973210), tolerance=0.00001))
  expect_that(cadotte.pd$cadotte.pd$Eed, is_equivalent_to(cadotte.pd$coefs$EED))
  expect_that(cadotte.pd$cadotte.pd$Hed, is_equivalent_to(cadotte.pd$coefs$HED))
})
test_that("Each measure is the same as calculated together", {
  all <- shape(data)
  expect_that(psv_test$psv, equals(all$psv))
  expect_that(psr_test$psr, equals(all$psr))
  expect_that(mpd_test$mpd, equals(all$mpd))
  expect_that(pd_test$pd, equals(all$pd))
  expect_that(pd_test$pd.ivs, equals(all$pd.ivs))
  expect_that(colless_test$colless, equals(all$colless))
  expect_that(gamma_test$gamma, equals(all$gamma))
  expect_that(taxon_test$taxon, equals(all$taxon))
  expect_that(eigen.sum$eigen.sum, equals(all$eigen.sum))
  expect_that(cadotte.pd$cadotte.pd, equals(all$cadotte.pd))
  expect_that(names(all), equals(c('psv','psr','mpd','pd','pd.ivs','colless','gamma','taxon','eigen.sum','cadotte.pd','type','coefs')))
  expect_that(names(all$coefs), equals(c('psv','psr','mpd','pd','pd.ivs','colless','gamma','Delta','DeltaStar','LambdaPlus','DeltaPlus','S.DeltaPlus','eigen.sum','EED','HED')))
  expect_that(all$coefs, equals(coef(all)))
})
